In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np 
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

# Blinkit Analysis

# Data Cleaning and Preprocessing

### Customer feedback data cleaning

In [2]:
cust_feedback=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_customer_feedback.csv")
delivery_perf=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_delivery_performance.csv")
customers=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_customers.csv")
inventory=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_inventoryNew.csv")
marketing_performance=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_marketing_performance.csv")
orders=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_orders.csv")
products=pd.read_csv(r"c:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Uncleaned CSV\Blinkit\blinkit_products.csv")

In [3]:
cust_feedback.shape

(5000, 8)

In [4]:
cust_feedback.head()

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20

In [5]:
cust_feedback.isna().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

In [6]:
cust_feedback["feedback_date"]=pd.to_datetime(cust_feedback["feedback_date"]) # converting data type
cust_feedback['year_month'] = cust_feedback['feedback_date'].dt.to_period('M')

# Preview
print(cust_feedback[['feedback_date', 'year_month']].head())

  feedback_date year_month
0    2024-07-17    2024-07
1    2024-05-28    2024-05
2    2024-09-23    2024-09
3    2023-11-24    2023-11
4    2023-11-20    2023-11

In [7]:
cust_feedback.drop(columns=["feedback_text","feedback_id","feedback_date"],inplace=True)

In [8]:
cust_feedback.head()

     order_id  customer_id  rating feedback_category sentiment year_month
0  1961864118     30065862       4          Delivery   Neutral    2024-07
1  1549769649      9573071       3    App Experience  Negative    2024-05
2  9185164487     45477575       3    App Experience   Neutral    2024-09
3  9644738826     88067569       4    App Experience   Neutral    2023-11
4  5427684290     83298567       3          Delivery  Negative    2023-11

In [9]:
cust_feedback.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           5000 non-null   int64
 1   customer_id        5000 non-null   int64
 2   rating             5000 non-null   int64
 3   feedback_category  5000 non-null   object
 4   sentiment          5000 non-null   object
 5   year_month         5000 non-null   period[M]
dtypes: int64(3), object(2), period[M](1)
memory usage: 234.5+ KB

### Delivery performance data cleaning

In [10]:
delivery_perf.head()

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic

In [11]:
delivery_perf.isna().sum()

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [12]:
delivery_perf.duplicated().sum()

np.int64(0)

In [13]:
delivery_perf.drop(columns=["promised_time","actual_time"],inplace=True)

In [14]:
delivery_perf.head()

,order_id,delivery_partner_id,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,-5.0,0.96,On Time,NaN
1,1549769649,14983,2.0,0.98,On Time,Traffic
2,9185164487,39859,4.0,3.83,On Time,Traffic
3,9644738826,61497,-1.0,2.76,On Time,NaN
4,5427684290,84315,1.0,2.63,On Time,Traffic

In [15]:
delivery_perf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5000 non-null   int64
 1   delivery_partner_id    5000 non-null   int64
 2   delivery_time_minutes  5000 non-null   float64
 3   distance_km            5000 non-null   float64
 4   delivery_status        5000 non-null   object
 5   reasons_if_delayed     3098 non-null   object
dtypes: float64(2), int64(2), object(2)
memory usage: 234.5+ KB

### Customers data cleaning

In [16]:
customers.shape

(2500, 11)

In [17]:
customers.head()

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14

In [18]:
customers.isna().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

In [19]:
customers.duplicated().sum()

np.int64(0)

In [20]:
customers.info()
customers.drop(columns=["email","pincode","phone","address"],inplace=True) # dropping less important columns which are not needed for business anlysis
customers["registration_date"]=pd.to_datetime(customers["registration_date"])
customers["registration_date"]=customers["registration_date"].dt.to_period("M")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   object
 2   email              2500 non-null   object
 3   phone              2500 non-null   int64
 4   address            2500 non-null   object
 5   area               2500 non-null   object
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   object
 8   customer_segment   2500 non-null   object
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(4), object(6)
memory usage: 215.0+ KB

In [21]:
customers.head()

,customer_id,customer_name,area,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,Udupi,2023-05,Premium,13,451.92
1,22077605,Megha Sachar,Aligarh,2024-06,Inactive,4,825.48
2,47822591,Hema Bahri,Begusarai,2024-09,Regular,17,1969.81
3,79726146,Zaitra Vig,Kozhikode,2023-10,New,4,220.09
4,57102800,Januja Verma,Ichalkaranji,2024-03,Inactive,14,578.14

In [22]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   object
 2   area               2500 non-null   object
 3   registration_date  2500 non-null   period[M]
 4   customer_segment   2500 non-null   object
 5   total_orders       2500 non-null   int64
 6   avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(2), object(3), period[M](1)
memory usage: 136.8+ KB

### inventory data cleaning

In [23]:
inventory.head()

   product_id    date  stock_received  damaged_stock
0      153019  Mar-23               4              1
1      848226  Mar-23               4              1
2      965755  Mar-23               1              0
3       39154  Mar-23               4              0
4       34186  Mar-23               3              1

In [24]:
inventory.shape

(18105, 4)

In [25]:
inventory.isna().sum()
inventory.duplicated().sum() #These duplicates are important so no need to remove them

np.int64(7359)

In [26]:
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18105 entries, 0 to 18104
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      18105 non-null  int64
 1   date            18105 non-null  object
 2   stock_received  18105 non-null  int64
 3   damaged_stock   18105 non-null  int64
dtypes: int64(3), object(1)
memory usage: 565.9+ KB

### Marketing performance data cleaning

In [27]:
marketing_performance.head()

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22

In [28]:
marketing_performance.isna().sum()

campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

In [29]:
marketing_performance.duplicated().sum()

np.int64(0)

In [30]:
marketing_performance.info()
marketing_performance["date"]=pd.to_datetime(marketing_performance["date"])
marketing_performance["date_fmt"] = marketing_performance["date"].dt.strftime("%Y-%m-%d") # fixing the format of the date column
marketing_performance["date_fmt"]=pd.to_datetime(marketing_performance["date_fmt"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   object
 2   date               5400 non-null   object
 3   target_audience    5400 non-null   object
 4   channel            5400 non-null   object
 5   impressions        5400 non-null   int64
 6   clicks             5400 non-null   int64
 7   conversions        5400 non-null   int64
 8   spend              5400 non-null   float64
 9   revenue_generated  5400 non-null   float64
 10  roas               5400 non-null   float64
dtypes: float64(3), int64(4), object(4)
memory usage: 464.2+ KB

In [31]:
marketing_performance["year_month"]=marketing_performance["date_fmt"].dt.to_period("M")

In [32]:
marketing_performance.drop(columns=["date","date_fmt"],inplace=True)

In [33]:
marketing_performance.head()

,campaign_id,campaign_name,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas,year_month
0,548299,New User Discount,Premium,App,3130,163,78,1431.85,4777.75,3.60,2024-11
1,390914,Weekend Special,Inactive,App,3925,494,45,4506.34,6238.11,2.98,2024-11
2,834385,Festival Offer,Inactive,Email,7012,370,78,4524.23,2621.00,2.95,2024-11
3,241523,Flash Sale,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84,2024-11
4,595111,Membership Drive,New Users,Email,7172,795,54,2888.99,8951.81,2.22,2024-11

In [34]:
marketing_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   object
 2   target_audience    5400 non-null   object
 3   channel            5400 non-null   object
 4   impressions        5400 non-null   int64
 5   clicks             5400 non-null   int64
 6   conversions        5400 non-null   int64
 7   spend              5400 non-null   float64
 8   revenue_generated  5400 non-null   float64
 9   roas               5400 non-null   float64
 10  year_month         5400 non-null   period[M]
dtypes: float64(3), int64(4), object(3), period[M](1)
memory usage: 464.2+ KB

### Orders data cleaning

In [35]:
orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [36]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   object
 3   promised_delivery_time  5000 non-null   object
 4   actual_delivery_time    5000 non-null   object
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 390.8+ KB

In [37]:
orders["order_date"]=pd.to_datetime(orders["order_date"])
orders['year_month'] = orders['order_date'].dt.to_period('M')

In [38]:
orders.drop(columns=["order_date",'promised_delivery_time','actual_delivery_time',"store_id"],inplace=True)

In [39]:
orders.head()

,order_id,customer_id,delivery_status,order_total,payment_method,delivery_partner_id,year_month
0,1961864118,30065862,On Time,3197.07,Cash,63230,2024-07
1,1549769649,9573071,On Time,976.55,Cash,14983,2024-05
2,9185164487,45477575,On Time,839.05,UPI,39859,2024-09
3,9644738826,88067569,On Time,440.23,Card,61497,2023-11
4,5427684290,83298567,On Time,2526.68,Cash,84315,2023-11

In [40]:
orders.isna().sum()
orders.duplicated().sum()

np.int64(0)

In [41]:
orders.head()

,order_id,customer_id,delivery_status,order_total,payment_method,delivery_partner_id,year_month
0,1961864118,30065862,On Time,3197.07,Cash,63230,2024-07
1,1549769649,9573071,On Time,976.55,Cash,14983,2024-05
2,9185164487,45477575,On Time,839.05,UPI,39859,2024-09
3,9644738826,88067569,On Time,440.23,Card,61497,2023-11
4,5427684290,83298567,On Time,2526.68,Cash,84315,2023-11

In [42]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             5000 non-null   int64
 1   customer_id          5000 non-null   int64
 2   delivery_status      5000 non-null   object
 3   order_total          5000 non-null   float64
 4   payment_method       5000 non-null   object
 5   delivery_partner_id  5000 non-null   int64
 6   year_month           5000 non-null   period[M]
dtypes: float64(1), int64(3), object(2), period[M](1)
memory usage: 273.6+ KB

### Products data cleaning

In [43]:
products.head()

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55

In [44]:
products.isna().sum()
products.duplicated().sum()

np.int64(0)

In [45]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    object
 3   brand              268 non-null    object
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.1+ KB

In [46]:
cust_feedback.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Customer feedback.csv",index=False)
delivery_perf.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Delivery performance.csv",index=False)
customers.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Customers.csv",index=False)

In [47]:
inventory.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Inventory.csv", index=False)

marketing_performance.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Marketing performance.csv", index=False)

orders.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Orders.csv", index=False)

products.to_csv(r"C:\Users\user\Desktop\Resume Project\Blinkit Analysis Excel\Cleaned CSV\Products.csv", index=False)

In [48]:
dfs = {
    "Customer Feedback": cust_feedback,
    "Delivery Performance": delivery_perf,
    "Customers": customers,
    "Inventory": inventory,
    "Marketing Performance": marketing_performance,
    "Orders": orders,
    "Products": products,
}

for name, df in dfs.items():
    print(f"\n--- {name} (Shape: {df.shape}) ---")
    display(df.head())

--- Customer Feedback (Shape: (5000, 6)) ---

     order_id  customer_id  rating feedback_category sentiment year_month
0  1961864118     30065862       4          Delivery   Neutral    2024-07
1  1549769649      9573071       3    App Experience  Negative    2024-05
2  9185164487     45477575       3    App Experience   Neutral    2024-09
3  9644738826     88067569       4    App Experience   Neutral    2023-11
4  5427684290     83298567       3          Delivery  Negative    2023-11

--- Delivery Performance (Shape: (5000, 6)) ---

,order_id,delivery_partner_id,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,-5.0,0.96,On Time,NaN
1,1549769649,14983,2.0,0.98,On Time,Traffic
2,9185164487,39859,4.0,3.83,On Time,Traffic
3,9644738826,61497,-1.0,2.76,On Time,NaN
4,5427684290,84315,1.0,2.63,On Time,Traffic

--- Customers (Shape: (2500, 7)) ---

,customer_id,customer_name,area,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,Udupi,2023-05,Premium,13,451.92
1,22077605,Megha Sachar,Aligarh,2024-06,Inactive,4,825.48
2,47822591,Hema Bahri,Begusarai,2024-09,Regular,17,1969.81
3,79726146,Zaitra Vig,Kozhikode,2023-10,New,4,220.09
4,57102800,Januja Verma,Ichalkaranji,2024-03,Inactive,14,578.14

--- Inventory (Shape: (18105, 4)) ---

   product_id    date  stock_received  damaged_stock
0      153019  Mar-23               4              1
1      848226  Mar-23               4              1
2      965755  Mar-23               1              0
3       39154  Mar-23               4              0
4       34186  Mar-23               3              1

--- Marketing Performance (Shape: (5400, 11)) ---

,campaign_id,campaign_name,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas,year_month
0,548299,New User Discount,Premium,App,3130,163,78,1431.85,4777.75,3.60,2024-11
1,390914,Weekend Special,Inactive,App,3925,494,45,4506.34,6238.11,2.98,2024-11
2,834385,Festival Offer,Inactive,Email,7012,370,78,4524.23,2621.00,2.95,2024-11
3,241523,Flash Sale,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84,2024-11
4,595111,Membership Drive,New Users,Email,7172,795,54,2888.99,8951.81,2.22,2024-11

--- Orders (Shape: (5000, 7)) ---

,order_id,customer_id,delivery_status,order_total,payment_method,delivery_partner_id,year_month
0,1961864118,30065862,On Time,3197.07,Cash,63230,2024-07
1,1549769649,9573071,On Time,976.55,Cash,14983,2024-05
2,9185164487,45477575,On Time,839.05,UPI,39859,2024-09
3,9644738826,88067569,On Time,440.23,Card,61497,2023-11
4,5427684290,83298567,On Time,2526.68,Cash,84315,2023-11

--- Products (Shape: (268, 10)) ---

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55