In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np 
import plotly.express as px

# Blinkit Analysis

In [5]:
cust_feedback=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_customer_feedback.csv")
delivery_perf=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_delivery_performance.csv")
customers=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_customers.csv")
inventory=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_inventoryNew.csv")
marketing_performance=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_marketing_performance.csv")
orders=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_orders.csv")
products=pd.read_csv(r"f:\Datasets\Blinkit\blinkit_products.csv")

In [6]:
print("Customers Shape:", customers.shape)
customers.head()

Customers Shape: (2500, 5)

,area,registration_date,customer_segment,total_orders,avg_order_value
0,Udupi,13-05-2023,Premium,13,451.92
1,Aligarh,18-06-2024,Inactive,4,825.48
2,Begusarai,25-09-2024,Regular,17,1969.81
3,Kozhikode,04-10-2023,New,4,220.09
4,Ichalkaranji,22-03-2024,Inactive,14,578.14

In [7]:
print("Inventory Shape:", inventory.shape)
inventory.head()

Inventory Shape: (18105, 3)

     date  stock_received  damaged_stock
0  Mar-23               4              1
1  Mar-23               4              1
2  Mar-23               1              0
3  Mar-23               4              0
4  Mar-23               3              1

In [8]:
print("Marketing Performance Shape:", marketing_performance.shape)
marketing_performance.head()

Marketing Performance Shape: (5400, 9)

,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated
0,New User Discount,05-11-2024,Premium,App,3130,163,78,1431.85,4777.75
1,Weekend Special,05-11-2024,Inactive,App,3925,494,45,4506.34,6238.11
2,Festival Offer,05-11-2024,Inactive,Email,7012,370,78,4524.23,2621.00
3,Flash Sale,05-11-2024,Inactive,SMS,1115,579,86,3622.79,2955.00
4,Membership Drive,05-11-2024,New Users,Email,7172,795,54,2888.99,8951.81

In [9]:
print("Orders Shape:", orders.shape)
orders.head()

Orders Shape: (5000, 6)

,order_date,delivery_time,actual_delivery_time,delivery_status,order_total,payment_method
0,Jul-24,Jul-24,17-07-2024 08:47,On Time,3197.07,Cash
1,May-24,May-24,28-05-2024 13:27,On Time,976.55,Cash
2,Sep-24,Sep-24,23-09-2024 13:29,On Time,839.05,UPI
3,Nov-23,Nov-23,24-11-2023 16:33,On Time,440.23,Card
4,Nov-23,Nov-23,20-11-2023 05:18,On Time,2526.68,Cash

In [10]:
print("Products Shape:", products.shape)
products.head()

Products Shape: (268, 8)

,product_name,category,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,Onions,Fruits & Vegetables,947.95,1263.93,25,3,13,88
1,Potatoes,Fruits & Vegetables,127.16,169.55,25,3,20,65
2,Potatoes,Fruits & Vegetables,212.14,282.85,25,3,23,70
3,Tomatoes,Fruits & Vegetables,209.59,279.45,25,3,10,51
4,Onions,Fruits & Vegetables,354.52,472.69,25,3,27,55

In [11]:
dfs = {
    "Customer Feedback": cust_feedback,
    "Delivery Performance": delivery_perf,
    "Customers": customers,
    "Inventory": inventory,
    "Marketing Performance": marketing_performance,
    "Orders": orders,
    "Products": products,
}

for name, df in dfs.items():
    print(f"\n--- {name} (Shape: {df.shape}) ---")
    display(df.head())

--- Customer Feedback (Shape: (5000, 3)) ---

   rating feedback_category sentiment
0       4          Delivery   Neutral
1       3    App Experience  Negative
2       3    App Experience   Neutral
3       4    App Experience   Neutral
4       3          Delivery  Negative

--- Delivery Performance (Shape: (5000, 5)) ---

,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status
0,17-07-2024 08:52,17-07-2024 08:47,-5,0.96,On Time
1,28-05-2024 13:25,28-05-2024 13:27,2,0.98,On Time
2,23-09-2024 13:25,23-09-2024 13:29,4,3.83,On Time
3,24-11-2023 16:34,24-11-2023 16:33,-1,2.76,On Time
4,20-11-2023 05:17,20-11-2023 05:18,1,2.63,On Time

--- Customers (Shape: (2500, 5)) ---

,area,registration_date,customer_segment,total_orders,avg_order_value
0,Udupi,13-05-2023,Premium,13,451.92
1,Aligarh,18-06-2024,Inactive,4,825.48
2,Begusarai,25-09-2024,Regular,17,1969.81
3,Kozhikode,04-10-2023,New,4,220.09
4,Ichalkaranji,22-03-2024,Inactive,14,578.14

--- Inventory (Shape: (18105, 3)) ---

     date  stock_received  damaged_stock
0  Mar-23               4              1
1  Mar-23               4              1
2  Mar-23               1              0
3  Mar-23               4              0
4  Mar-23               3              1

--- Marketing Performance (Shape: (5400, 9)) ---

,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated
0,New User Discount,05-11-2024,Premium,App,3130,163,78,1431.85,4777.75
1,Weekend Special,05-11-2024,Inactive,App,3925,494,45,4506.34,6238.11
2,Festival Offer,05-11-2024,Inactive,Email,7012,370,78,4524.23,2621.00
3,Flash Sale,05-11-2024,Inactive,SMS,1115,579,86,3622.79,2955.00
4,Membership Drive,05-11-2024,New Users,Email,7172,795,54,2888.99,8951.81

--- Orders (Shape: (5000, 6)) ---

,order_date,delivery_time,actual_delivery_time,delivery_status,order_total,payment_method
0,Jul-24,Jul-24,17-07-2024 08:47,On Time,3197.07,Cash
1,May-24,May-24,28-05-2024 13:27,On Time,976.55,Cash
2,Sep-24,Sep-24,23-09-2024 13:29,On Time,839.05,UPI
3,Nov-23,Nov-23,24-11-2023 16:33,On Time,440.23,Card
4,Nov-23,Nov-23,20-11-2023 05:18,On Time,2526.68,Cash

--- Products (Shape: (268, 8)) ---

,product_name,category,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,Onions,Fruits & Vegetables,947.95,1263.93,25,3,13,88
1,Potatoes,Fruits & Vegetables,127.16,169.55,25,3,20,65
2,Potatoes,Fruits & Vegetables,212.14,282.85,25,3,23,70
3,Tomatoes,Fruits & Vegetables,209.59,279.45,25,3,10,51
4,Onions,Fruits & Vegetables,354.52,472.69,25,3,27,55

In [12]:
cust_feedback.head()

   rating feedback_category sentiment
0       4          Delivery   Neutral
1       3    App Experience  Negative
2       3    App Experience   Neutral
3       4    App Experience   Neutral
4       3          Delivery  Negative

In [13]:
cust_feedback.isna().sum()

rating               0
feedback_category    0
sentiment            0
dtype: int64